export const HANDLE_ADD_TO_CART_REQUEST = 'HANDLE_ADD_TO_CART_REQUEST'
export const HANDLE_ADD_TO_CART_SUCCESS = 'HANDLE_ADD_TO_CART_SUCCESS'
export const HANDLE_ADD_TO_CART_ERROR = 'HANDLE_ADD_TO_CART_ERROR'

export const GET_CART_ITEMS = 'GET_CART_ITEMS'

export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const GET_TOTAL_AND_COUNT = 'GET_TOTAL_AND_COUNT'
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'
export const EMPTY_CART_ITEMS = 'EMPTY_CART_ITEMS'

export const PROCEED_TO_CHECKOUT_REQUEST = 'PROCEED_TO_CHECKOUT_REQUEST'
export const PROCEED_TO_CHECKOUT_SUCCESS = 'PROCEED_TO_CHECKOUT_SUCCESS'
export const PROCEED_TO_CHECKOUT_ERROR = 'PROCEED_TO_CHECKOUT_ERROR'

