export const LIST_PRODUCTS_REQUEST = 'LIST_PRODUCTS_REQUEST'
export const LIST_PRODUCTS_SUCCESS = 'LIST_PRODUCTS_SUCCESS'
export const LIST_PRODUCTS_ERROR = 'LIST_PRODUCTS_ERROR'

export const ADD_TO_CART = 'ADD_TO_CART'
export const PRODUCT_DELETE_CART_ITEM = 'PRODUCT_DELETE_CART_ITEM'
export const PRODUCT_EMPTY_CART_ITEMS = 'PRODUCT_EMPTY_CART_ITEMS'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_ERROR = 'PRODUCT_DETAILS_ERROR'